dusk-network/rusk-vm

Cargo.toml, dusk-abi/Cargo.toml, dusk-abi/src/lib.rs, src/ops/poseidon_hash.rs, src/ops/verify_proof.rs, tests/contracts/verify_proof/src/lib.rs, tests/lib.rs
- Adds `CorrectnessCircuit` as a new entry in the `verify_proof` ABICall map. Closes #149 
- Updates the deps to the latest versions pulling from crates.io when possible. Closes #152
=> Add CorrectnessCircuit to the verify_proof ABICall map

Cargo.toml
For some weird behavior the bump to `0.4.0` wasn't applied.
Looks like it was considered somehow as no part of this repo.
See also: <https://github.com/dusk-network/rusk-vm/commit/d20219b07568758c8e3cda76f384cfdd9f7548e8>
- Remove unused deps from Cargo.toml
=> Bump to `0.4.0` (again)

Cargo.toml, src/contract.rs, src/lib.rs, src/state.rs, tests/contracts/counter_float/Cargo.toml, tests/contracts/counter_float/Makefile, tests/contracts/counter_float/rustfmt.toml, tests/contracts/counter_float/src/lib.rs, tests/lib.rs
As stated in #115 and #116 we need a way to instrumentate the WASM
bytecode of the contracts deployed to be able to inject gas_metering
tools as well as removal of floating point operations among other
checks.
This PR adds the tooling and instrumentation linked to the
`NetworksState::deploy()` fn adding the following checks and
instrumentation for the bytecode:
- No floating point ops are used in the contract.
- Gas metering tools are injected correctly and work.
- Stack height metering tools so that we never pass the maximum allowed.
- Table size limits used in the wasm Modules are not bigger than what is
allowed.
- Validity check of all of the previous instrumentation.
Resolves: #115, #116.
This leaves as a new issue to address: #174
=> Implement bytecode instrumentation at deploy time

.github/workflows/dusk_ci.yml, tests/lib.rs
The test was failing because a more recent nightly was used in the CI,
instead of using the version specified in `rust-toolchain`.
Locally everything was working properly because the overrides was on the
CI config file.
Without the override both CI and local execution are using the same
version specified in `rust-toolchain`.
P.S.
Notice that on our custom runner this is not fixed since we have an additional problem that should be fixed separately – conflict with existing version of rust, looks like the runner is not properly sandboxed –, so basically trying to fix this issue there was even more complicated: in fact, even with this fix, the test is still failing on self-hosted.
Resolves: #229
=> Remove rust toolchain overrides from CI

.github/codecov.yml, .github/workflows/dusk_ci.yml, Makefile, tests/Makefile
Adds code coverage generation to the CI, publishing it to [codecov](https://about.codecov.io).
=> Add codecov to CI

src/call_context.rs, src/gas.rs, src/lib.rs, src/ops/gas.rs, src/ops/query.rs, src/ops/transact.rs, src/state.rs, tests/contracts/gas_context/src/lib.rs, tests/gas_context.rs, tests/lib.rs
- Add `GasMeter::RESERVE_PERCENTAGE` as associated constant
- Add `GasMeter::limited` method
- Add mutable `GasMeter` reference to `StackFrame`
- Add `StackFrame::new` associated function
- Remove `Argument` field from `StackFrame`
- Remove `StackFrame::new_query` and `StackFrame::new_transaction`
- Remove `GasMeter` from `CallContext`
- Remove `GasMeter.held` private field
- Remove `GasMeter::with_range` associated function
- Remove `gas_constants` module
- Replace `GasMeterResult` with `GasError`
- Remove `GasMeter::gas_left` method, deprecated since 0.6
- Remove `GasMeter::total_left` method
- Remove `GasMeter::clone_for_callee_default` method
- Remove `GasMeter::clone_for_callee` method
- Remove `GasMeter::merge_with_callee` method
- Updated tests
Resolves: #254
=> Refactor contextual `GasMeter`

src/call_context.rs, src/gas.rs
It is a proposal to make stack frame pure functional, i.e., not having references. This make reasoning about stack frame much easier as there are no side effects when dealing with it and all effects needs to be explicit.
It addresses the issue: 
https://github.com/dusk-network/rusk-vm/issues/254
=> Make stackframe pure functional

CHANGELOG.md, src/call_context.rs, src/ops/block_height.rs, src/state.rs, tests/gas_context.rs, tests/lib.rs, tests/stack.rs
This change removes the block height from `NetworkState`.
The reasoning behind this is that not only that the VM shouldn't have to care about block_height, but also that this significantly simplifies reasoning about the logic in solving [this issue](https://github.com/dusk-network/rusk-vm/issues/263).
=> Remove `block_height` from network state

CHANGELOG.md, src/call_context.rs, src/contract.rs, src/lib.rs, src/modules.rs, src/state.rs
Wraps the type of the `NetworkState::modules` field in the `HostModules` structure.
Resolves: #270
=> Wrap `NetworkState::modules`' type in a struct

CHANGELOG.md, Cargo.toml, src/call_context.rs, src/gas.rs, src/lib.rs, src/state.rs, tests/lib.rs
This PR is intended to address the transaction rollbacks problem described in #263.
The change entails keeping two states in memory - the `origin` and the `head` state. The caller can choose to perform queries or transactions on either, and the result of transactions will is kept in the `head` state.
When the user deems that enough transactions have been performed on the state they can call `commit` to copy the `head` into the origin.
If the users finds that for some reason they want to discard the state, they can call `reset` to copy `origin` into `head`.
=> Support TX rollbacks

CHANGELOG.md, src/state.rs
The implementation is currently very slow. Making it faster is contingent on microkelvin allowing for a direct [query of the root](https://github.com/dusk-network/microkelvin/issues/85).
Resolves: #265
=> Add support for reading the state root

CHANGELOG.md, Cargo.toml
- Update CHANGELOG.md
**Note**
Due the incoming breaking changes, the release candidate of 0.7 should be published, so we can move to `0.8`.
This PR is to prepare the library to be published in crates.io
=> Bump to `v0.7.0`

CHANGELOG.md, Cargo.toml, src/call_context.rs, src/state.rs, src/state/persist.rs, tests/lib.rs, tests/multiple_state.rs, tests/stack.rs
- Add `staged` state in addition to the existing `head` and `origin`
- Add `unstage` method to remove changes from `staged`
- Change `commit` method to commit the changes from `staged` to `head`
- Add `push` method to push the commited changes to `origin`
- Change `register_host_module` to be an associated function
- Add new tests and update existing ones
Resolves: #302
=> The VM needs to handle three different states instead of two

CHANGELOG.md, Cargo.toml, src/call_context.rs, src/gas.rs, src/lib.rs, src/ops/call_stack.rs, src/ops/gas.rs, src/ops/query.rs, src/ops/transact.rs, src/resolver.rs, tests/contracts/gas_consumed/src/lib.rs, tests/lib.rs
- Add `exhaust` method to `GasMeter`
- Add a private `update` method to `GasMeter`
- Add `VMError::EmptyStack`
- Add `Instance` field to `StackFrame` 
- Add `CallContext::top_mut()`
- Add new `CallContext::gas_meter` method in `ops` module
- Replace `GasMeter::set_left(0)` with `GasMeter::exhaust()` 
- Change `CallContext::top()` to return a `Result`
- Change `CallContext::gas_meter()` to update the gas meter before return it
- Remove `set_left` method from `GasMeter` 
- Remove legacy `gas` host function
- Remove `CallContext::gas_meter_mut()`
- Remove `Gas` host function implementation from `ops` module
Resolves #308
=> Release 0.11.0-rc.0 with Gas fixed

Cargo.toml, tests/contracts/map/Cargo.toml, tests/contracts/map/Makefile, tests/contracts/map/rustfmt.toml, tests/contracts/map/src/lib.rs, tests/lib.rs
This test is added to ensure that `dusk-hamt` can be compiled and used properly in `wasm32` target architecture.
=> Add simple dusk-hamt test to the test suite

Cargo.toml, src/call_context.rs, src/error.rs, src/lib.rs, src/modules.rs, src/ops/panic.rs, src/ops/query.rs, src/ops/store.rs, src/ops/transact.rs, src/state.rs, src/state/persist.rs, tests/contracts/callee-1/src/lib.rs, tests/contracts/callee-2/src/lib.rs, tests/contracts/caller/src/lib.rs, tests/contracts/counter_float/Cargo.toml, tests/lib.rs
- Change `VMError` to be in its own `error` module
- Add `Debug` trait to `VMError`
- Add `Display` and `std::error::Error` traits to `InstrumentationError`
- Change syntax to `thiserror` to simplify conversion and display messages
- Remove `VMError::from_store_error`
- Remove unused errors.
Here the list of the errors removed:
InvalidArguments, MemoryNotFound, InvalidABICall,
InvalidEd25519PublicKey, InvalidEd25519Signature, ContractReturn,
NotEnoughFunds, WASMError, InvalidWASMModule,
PersistenceSerializationError, PersistenceError,
- Change how the conversion from `wasmer::RuntimeError` to `VMError` is
done.
Now we `downcast` to `VMError` if `wasmer::RuntimeError` is a wrapper
to a `VMError`.
- Add test for `UnknownContract` error
- Add test for `ContractPanic` error
- Update …
=> Improve VMError Implementation

.github/workflows/dusk_ci.yml, Cargo.toml, src/contract.rs, src/error.rs, src/lib.rs, src/ops/store.rs, src/state.rs, src/state/persist.rs, test_runner/Cargo.toml, test_runner/src/main.rs, tests/contracts/block_height/Cargo.toml, tests/contracts/callee-1/Cargo.toml, tests/contracts/callee-2/Cargo.toml, tests/contracts/caller/Cargo.toml, tests/contracts/counter/Cargo.toml, tests/contracts/counter_float/Cargo.toml, tests/contracts/delegator/Cargo.toml, tests/contracts/fibonacci/Cargo.toml, tests/contracts/gas_consumed/Cargo.toml, tests/contracts/gas_context/Cargo.toml, tests/contracts/host_fn/Cargo.toml, tests/contracts/map/Cargo.toml, tests/contracts/map/src/lib.rs, tests/contracts/self_snapshot/Cargo.toml, tests/contracts/stack/Cargo.toml, tests/contracts/tx_vec/Cargo.toml, tests/contracts/tx_vec/src/lib.rs, tests/lib.rs, tests/stack.rs
- Improved map contract and test
- Add session test for dusk-hamt map
- Change store ops to always use microkelvin
- Bump versions across canonical, microkelvin and dusk-abi
- Add proper `PersistError` to `VMError`
Resolves #312
=> Update to `microkelvin` 0.15 and `canonical` 0.7

Cargo.toml, rusk-uplink/src/definitions.rs, rusk-uplink/src/hosted.rs, src/call_context.rs, src/ops/emit.rs, src/ops/mod.rs, src/resolver.rs, src/state.rs, tests/contracts/events/Cargo.toml, tests/contracts/events/Makefile, tests/contracts/events/rustfmt.toml, tests/contracts/events/src/lib.rs, tests/contracts/stack/src/lib.rs, tests/dual_test.rs, tests/gas_context.rs, tests/lib.rs
This PR implements an event system. It works by introducing a new host import - named `emit` - that when called pushes an event onto a list. The list is subsequently returned - wrapped in a `Receipt` - together with the result of the call.
Each event contains the following data:
```rust
pub struct Event {
origin: ContractId, // originating smart contract ID
name: String,       // name of the type of event
data: Vec<u8>,      // arbitrary data emitted with the event
}
```
The smart contract engineer has the option of passing any structure implementing `Archive` and`Serialize<StoreSerializer<OffsetLen>>` and have it be emitted as an event.
Resolves #326
=> Event system implementation

CHANGELOG.md, benches/stack.rs, src/state.rs, src/state/persist.rs, test_runner/src/main.rs, tests/configuration.rs, tests/contracts/delegator/src/lib.rs, tests/contracts/register/src/lib.rs, tests/contracts/tx_vec/src/lib.rs, tests/dual_test.rs, tests/gas_context.rs, tests/gas_usage.rs, tests/lib.rs
State management was previously done as a quick way to be able to manage
multiple states at the same time. This change makes the user responsible
for when they *keep* the state resulting from a transaction, as opposed
to when they *discard* said state.
Resolves #357
=> Remove state management

CHANGELOG.md, benches/fibonacci.rs, benches/stack.rs, rusk-uplink/src/definitions.rs, rusk-uplink/src/framing.rs, src/lib.rs, src/modules.rs, src/state.rs, src/state/builder.rs, src/state/persist.rs, test_runner/src/main.rs, tests/configuration.rs, tests/dual_test.rs, tests/gas_context.rs, tests/gas_usage.rs, tests/lib.rs
This changes the instantiation and persistence mechanism of a `NetworkState` by adding a builder. This has the rather pleasant consequence that the user doesn't need to keep store references, with the notable exception of add-hoc instantiating and adding contracts to the state.
Resolves #319
=> Change `NetworkState` construction and persistance
