dusk-network/rusk-vm

- Cargo.toml
- src/call_context.rs
- src/ops/call_contract.rs
- src/ops/mod.rs
- src/ops/opcode.rs
- src/ops/phoenix_ops.rs
- src/resolver.rs
- src/state.rs
See also:
dusk-network/rusk#8
dusk-network/rusk#28
dusk-network/dusk-abi#2
> Add back phoenix's ops and add opcode host function

- tests/contracts/storage_factorial/src/lib.rs
- tests/lib.rs
> Fix failing storage_factorial test

- Cargo.toml
- Makefile
- dusk-abi/Cargo.toml
- dusk-abi/src/lib.rs
- src/ops/mod.rs
- src/ops/poseidon_hash.rs
- src/resolver.rs
- tests/contracts/hash/Cargo.toml
- tests/contracts/hash/rustfmt.toml
- tests/contracts/hash/src/lib.rs
- tests/lib.rs
- Add `dusk_abi::poseidon_hash`
- Add test contract
Resolves: #131
See also: #123
> Add Poseidon Sponge Hash function as Host function

- dusk-abi/src/lib.rs
- src/ops/block_height.rs
- src/ops/mod.rs
- src/resolver.rs
- src/state.rs
- tests/contracts/hash/src/lib.rs
- tests/lib.rs
- Add `NetworkState::with_block_height()` constructor
Resolves: #128
> Add `block_height` as host function

- Cargo.toml
- Makefile
- src/call_context.rs
- src/gas.rs
- src/ops/callee.rs
- src/ops/debug.rs
- src/ops/panic.rs
- src/ops/query.rs
- src/ops/store.rs
- src/ops/transact.rs
- src/state.rs
- tests/contracts/block_height/Cargo.toml
- tests/contracts/counter/Cargo.toml
- tests/contracts/delegator/Cargo.toml
- tests/contracts/delegator/src/lib.rs
- tests/contracts/fibonacci/Cargo.toml
- tests/contracts/host_fn/Cargo.toml
- tests/contracts/self_snapshot/Cargo.toml
- tests/contracts/self_snapshot/Makefile
- tests/contracts/self_snapshot/rustfmt.toml
- tests/contracts/self_snapshot/src/lib.rs
- tests/contracts/stack/Cargo.toml
- tests/contracts/verify_proof/Cargo.toml
- tests/lib.rs
- Update to `dusk-abi` v0.6
- Add proper error handling where it was still missing
- Remove "FIXME" for the error handling
- Fix few lint warnings
- Add "update and panic" test to self_snapshot contract
- Change `get_contract_state` to `get_contract_cast_state`
- Add tests
Resolves: #163
> Test for self snapshots

- Cargo.toml
- src/call_context.rs
- src/ops/call_stack.rs
- src/ops/mod.rs
- src/resolver.rs
- tests/contracts/callee-1/Cargo.toml
- tests/contracts/callee-1/Makefile
- tests/contracts/callee-1/rustfmt.toml
- tests/contracts/callee-1/src/lib.rs
- tests/contracts/callee-2/Cargo.toml
- tests/contracts/callee-2/Makefile
- tests/contracts/callee-2/rustfmt.toml
- tests/contracts/callee-2/src/lib.rs
- tests/contracts/caller/Cargo.toml
- tests/contracts/caller/Makefile
- tests/contracts/caller/rustfmt.toml
- tests/contracts/caller/src/lib.rs
- tests/lib.rs
> Implement `dusk-abi::caller`

- Cargo.toml
- benches/stack.rs
- src/call_context.rs
> Benchmark the stack contract

- Cargo.toml
> Bump to 0.6.0

- src/state.rs
> Add a method to mutate NetworkState block_height

- Cargo.toml
- Makefile
- src/state.rs
- tests/lib.rs
> Change persist-related code to be behind feat flag 

- Cargo.toml
- src/state.rs
- tests/lib.rs
> Add `deploy_with_id` method to `NetworkState`

- README.md
Fixes the displayed badges to display Github CI and codecov code coverage.
> Fix displayed badges

- CHANGELOG.md
- Cargo.toml
- src/compiler_config.rs
- Bump to `0.7.0-rc.3`
- Update CHANGELOG.md
Resolves: #283
> Add Cranelift for non `x86_64` arch

- src/state.rs
Really small fix to the docs of `NetworkState`.
> Fix `NetworkState` docs

- CHANGELOG.md
- Cargo.toml
- src/compiler_config.rs
- Change the compiler to use always `Singlepass`
- Update CHANGELOG
- Bump to `0.12.0-rc.1`
Resolves #337
> Use singlepass compiler on Apple Silicon too

- rusk-uplink/src/definitions.rs
- src/call_context.rs
- src/error.rs
- src/lib.rs
- src/modules.rs
- src/ops/panic.rs
- src/state.rs
- src/state/persist.rs
- tests/lib.rs
VM2 error related improvements
Solves issue #329
> VM2 error related improvements

- .github/workflows/dusk_ci.yml
See also https://github.com/dusk-network/rusk-vm/issues/325
> Fix `kcov` to fail when tests fail

- CHANGELOG.md
- src/call_context.rs
- src/contract.rs
- src/lib.rs
- src/state.rs
- test_runner/src/main.rs
> Place both contract code and state behind link

- Cargo.toml
- tests/contracts/map/Cargo.toml
- tests/contracts/map/Makefile
- tests/contracts/map/rustfmt.toml
- tests/contracts/map/src/lib.rs
- tests/lib.rs
> Forward port `dusk-hamt` test

- CHANGELOG.md
- src/config.rs
- src/ops/store.rs
- tests/configuration.rs
> Make `put` host call charge gas per byte

- .github/workflows/dusk_ci.yml
> Change CI to run on self-hosted server
